Input Validation for N in Sim 1
ccnmtl/metricsmentor pull request #271
Opened 2024-05-24 15:41 UTC by Evan-CTL

2024-05-24 15:51 UTC, zmustapha commented
I could still type any number larger than 500

2024-05-24 18:26 UTC, ndittren submitted a review, later dismissed
I think this can be better achieved by taking advantage of HTML event changes. We can add another state that will be handled by the onChange and make the necessary validation with an onBlur. The handleNBlur function would be the one to make the validation checks. These changes can be done just in simulationOne.jsx

2024-05-28 17:22 UTC, Evan-CTL commented
> I think this can be better achieved by taking advantage of HTML event changes. We can add another state that will be handled by the onChange and make the necessary validation with an onBlur. The handleNBlur function would be the one to make the validation checks. These changes can be done just in simulationOne.jsx

Agreed. Changes made

2024-05-29 19:34 UTC, ndittren requested changes
Address comment left on simulationOne.jsx line 54

2024-05-29 20:05 UTC, Evan-CTL commented on media/js/src/simulationOne/simulationOne.jsx
> +        setN(parseInt(e.target.value) || N);
Oh, that was what the review was hanging on. It didn't pop up in the conversation. My mistake.

2024-05-29 20:21 UTC, ndittren approved these changes

2024-05-29 20:22 UTC, merged